version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./amazon_reviews.csv:/amazon_reviews.csv
      - ./google_books.csv:/google_books.csv
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: admin

  arangodb:
    image: arangodb/arangodb:latest
    container_name: arangodb
    ports:
      - "8529:8529"
    volumes:
      - ./amazon_reviews.csv:/import/amazon_reviews.csv
      - ./google_books.csv:/import/google_books.csv
    environment:
      ARANGO_ROOT_PASSWORD: rootpassword
    restart: unless-stopped

volumes:
  mongo-data:

  # ravendb-node1:
  #   container_name: ravendb-node1
  #   image: ravendb/ravendb:latest
  #   ports:
  #     - 8080:8080
  #     - 38888:38888
  #   volumes:
  #     - /home/${USER}/ravendb/data/node1:/var/lib/ravendb/data
  #   environment:
  #     - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
  #     - RAVEN_Setup_Mode=None
  #     - RAVEN_License_Eula_Accepted=true
  #     - RAVEN_ServerUrl=http://0.0.0.0:8080
  #     - RAVEN_PublicServerUrl=http://${HOST_IP}:8080
  #     - RAVEN_ServerUrl_Tcp=tcp://0.0.0.0:38888
  #     - RAVEN_PublicServerUrl_Tcp=tcp://${HOST_IP}:38888
  #     - RAVEN_License={PUT YOUR LICENSE HERE}

  # ravendb-node2:
  #   container_name: ravendb-node2
  #   image: ravendb/ravendb:latest
  #   ports:
  #     - 8081:8080
  #     - 38889:38888
  #   volumes:
  #     - /home/${USER}/ravendb/data/node2:/var/lib/ravendb/data
  #   environment:
  #     - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
  #     - RAVEN_Setup_Mode=None
  #     - RAVEN_License_Eula_Accepted=true
  #     - RAVEN_ServerUrl=http://0.0.0.0:8080
  #     - RAVEN_PublicServerUrl=http://${HOST_IP}:8081
  #     - RAVEN_ServerUrl_Tcp=tcp://0.0.0.0:38888
  #     - RAVEN_PublicServerUrl_Tcp=tcp://${HOST_IP}:38889
  #     - RAVEN_License={PUT YOUR LICENSE HERE}

  # ravendb-node3:
  #   container_name: ravendb-node3
  #   image: ravendb/ravendb:latest
  #   ports:
  #     - 8082:8080
  #     - 38890:38888
  #   volumes:
  #     - /home/${USER}/ravendb/data/node3:/var/lib/ravendb/data
  #   environment:
  #     - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
  #     - RAVEN_Setup_Mode=None
  #     - RAVEN_License_Eula_Accepted=true
  #     - RAVEN_ServerUrl=http://0.0.0.0:8080
  #     - RAVEN_PublicServerUrl=http://${HOST_IP}:8082
  #     - RAVEN_ServerUrl_Tcp=tcp://0.0.0.0:38888
  #     - RAVEN_PublicServerUrl_Tcp=tcp://${HOST_IP}:38890
  #     - RAVEN_License={PUT YOUR LICENSE HERE}

  # mongo-express:
  #   image: mongo-express:latest
  #   container_name: mongo-express
  #   restart: always
  #   ports:
  #     - "8081:8081" # Expose Mongo Express sur localhost
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: admin
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: admin123  # Assurez-vous que le mot de passe correspond à celui de MongoDB
  #     ME_CONFIG_MONGODB_SERVER: mongo
  #     ME_CONFIG_BA_USERNAME: admin  # Ajout des identifiants pour l'authentification dans l'interface de Mongo Express
  #     ME_CONFIG_BA_PASSWORD: admin123


